ACS/Models/Partner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ACS.Models
{
    public class Partner
    {
        [Key]
        public int PartnerID { get; set; }

        [Required(ErrorMessage = "You must enter {0}")]
        [StringLength(30)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "You must enter {0}")]
        [StringLength(30)]
        public string Name { get; set; }

        [Required(ErrorMessage ="You must enter {0}")]
        [StringLength(15)]
        public string DocumentNumber { get; set; }

        [Required(ErrorMessage ="You must enter {0}")]
        public int DocumentTypeID { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [StringLength(80)]
        public string Address { get; set; }

        [Required(ErrorMessage = "You must enter {0}")]
        [StringLength(30)]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }

        public int? PartnerHeadOfFamilyID { get; set; }

        public string FullName { get { return string.Format("{0} {1}", LastName, Name); } }

        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<MonthlyFee> MonthlyFees { get; set; }
        public virtual ICollection<MonthlyFeeDetail> MonthlyFeeDetails { get; set; }

    }
}

ACS/Controllers/PartnersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ACS.Models;
using ACS.ViewModels;

namespace ACS.Controllers
{
    [Authorize(Roles = "Administrator, Employee")]
    public class PartnersController : Controller
    {
        private ACSContext db = new ACSContext();

        // GET: Partners
        public ActionResult Index()
        {
            var partners = db.Partners.Include(p => p.DocumentType).Where(h => h.PartnerHeadOfFamilyID == 0);
            return View(partners.ToList());
        }

        // GET: IndexFamilyGroup
        public ActionResult IndexFamilyGroup(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var partners = db.Partners.Include(p => p.DocumentType).Where(h => h.PartnerHeadOfFamilyID == id);
            ViewBag.PartnerHeadOfFamilyID = id;
            return View(partners.ToList());
        }

        // GET: SportsList
        public ActionResult SportList(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var partnerSportsView = new PartnerSportView();
            var partner = db.Partners.Find(id);
            partnerSportsView.Sport = new Sport();
            partnerSportsView.Sports = new List<Sport>();
            partnerSportsView.Partner = new Partner {
                LastName = partner.LastName,
                Name = partner.Name,
                PartnerID = partner.PartnerID,
                PartnerHeadOfFamilyID = partner.PartnerHeadOfFamilyID
            };
            var sportsID = db.PartnerSport.Where(p => p.PartnerID == id).Select(s => s.SportID).ToList();
            foreach (var item in sportsID)
            {
                var sport = db.Sports.Find(item);
                partnerSportsView.Sports.Add(sport);
            }
            Session["partnerSportsView"] = partnerSportsView;

            return View(partnerSportsView);
        }

        //GET AddSport
        public ActionResult AddSport()
        {
            var listS = GetSports();
            ViewBag.SportID = new SelectList(listS, "SportID", "Description");
            return View();
        }

        [HttpPost]
        public ActionResult AddSport(Sport sport)
        {
            var partnerSportsView = Session["partnerSportsView"] as PartnerSportView;
            var sportID = int.Parse(Request["SportID"]);
            if (sportID == 0)
            {
                var list = GetSports();
                ViewBag.SportID = new SelectList(list, "SportID", "Description");
                ViewBag.Error = "You must select a Sport.";
                return View();
            }

            var sportF = db.Sports.Find(sportID);

            var partnerSportID = partnerSportsView.Sports.Find(s => s.SportID == sportF.SportID);
            if (partnerSportID == null)
            {
                partnerSportsView.Sports.Add(sportF);
                var partnerSport = new PartnerSport
                {
                    PartnerID = partnerSportsView.Partner.PartnerID,
                    SportID = sportF.SportID
                };
                db.PartnerSport.Add(partnerSport);
                db.SaveChanges();
            }
            

            

            return View("SportList", partnerSportsView);
        }

        // DeleteSport
        public ActionResult DeleteSport(int sportID, int partnerID)
        {
            if (sportID == 0 || partnerID == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var partner = db.Partners.Find(partnerID);
            var sport = db.Sports.Find(sportID);
            var partnerSport = db.PartnerSport.First(p => p.SportID == sportID && p.PartnerID == partnerID);
            db.PartnerSport.Remove(partnerSport);
            try
            {
                db.SaveChanges();
            }
            catch (Exception)
            {
                
            }

            var partnerSportsView = new PartnerSportView();
            
            partnerSportsView.Sport = new Sport();
            partnerSportsView.Sports = new List<Sport>();
            partnerSportsView.Partner = new Partner
            {
                LastName = partner.LastName,
                Name = partner.Name,
                PartnerID = partner.PartnerID,
                PartnerHeadOfFamilyID = partner.PartnerHeadOfFamilyID
            };
            var sportsID = db.PartnerSport.Where(p => p.PartnerID == partnerID).Select(s => s.SportID).ToList();
            foreach (var item in sportsID)
            {
                var sportP = db.Sports.Find(item);
                partnerSportsView.Sports.Add(sportP);
            }
            Session["partnerSportsView"] = partnerSportsView;

            return View("SportList", partnerSportsView);

        }

        // GET: Partners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partner partner = db.Partners.Find(id);
            if (partner == null)
            {
                return HttpNotFound();
            }
            return View("Details", partner);
        }

        // GET: Partners/Create
        public ActionResult Create()
        {
            var list = GetDocumentType();
            ViewBag.DocumentTypeID = new SelectList(list, "DocumentTypeID", "Description");
            return View();
        }

        // GET: Partners/Create
        public ActionResult CreateFamily(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var list = GetDocumentType();
            ViewBag.DocumentTypeID = new SelectList(list, "DocumentTypeID", "Description");
            var partner = new Partner {
                PartnerHeadOfFamilyID = id
            };
            return View("Create", partner);
        }

        // POST: Partners/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PartnerID,LastName,Name,DocumentNumber,DocumentTypeID,Phone,Address,EMail,PartnerHeadOfFamilyID")] Partner partner)
        {
            
            if (ModelState.IsValid)
            {
                if (partner.PartnerHeadOfFamilyID == null)
                {
                    partner.PartnerHeadOfFamilyID = 0;
                }                
                db.Partners.Add(partner);
                db.SaveChanges();
                if (partner.PartnerHeadOfFamilyID == 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return RedirectToAction("IndexFamilyGroup", new { id = partner.PartnerHeadOfFamilyID});
                }
                
            }
            var list = GetDocumentType();
            ViewBag.DocumentTypeID = new SelectList(list, "DocumentTypeID", "Description", partner.DocumentTypeID);
            return View(partner);
        }

        // GET: Partners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partner partner = db.Partners.Find(id);
            if (partner == null)
            {
                return HttpNotFound();
            }
            var list = GetDocumentType();
            ViewBag.DocumentTypeID = new SelectList(list, "DocumentTypeID", "Description", partner.DocumentTypeID);
            return View(partner);
        }

        // POST: Partners/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PartnerID,LastName,Name,DocumentNumber,DocumentTypeID,Phone,Address,EMail,PartnerHeadOfFamilyID")] Partner partner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(partner).State = EntityState.Modified;
                db.SaveChanges();
                if (partner.PartnerHeadOfFamilyID == 0)
                {
                    return RedirectToAction("Index", new { id = partner.PartnerHeadOfFamilyID });
                }
                else
                {
                    return RedirectToAction("IndexFamilyGroup", new { id = partner.PartnerHeadOfFamilyID });
                }                
            }
            var list = GetDocumentType();
            ViewBag.DocumentTypeID = new SelectList(list, "DocumentTypeID", "Description", partner.DocumentTypeID);
            return View(partner);
        }

        // GET: Partners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partner partner = db.Partners.Find(id);
            if (partner == null)
            {
                return HttpNotFound();

ACS/Views/Partners/AddSport.cshtml
@model ACS.Models.Sport
@{
    ViewBag.Title = "AddSport";
}
<h2>Add Sport</h2>
<h3>@ViewBag.Error</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.SportID, "SportID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SportID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SportID, "", new { @class = "text-danger" })
            </div>
        </div>
        <input type="submit" value="Add Sport" class="btn btn-default" />
    </div>
}


ACS/Views/Partners/Create.cshtml
@model ACS.Models.Partner

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Partners", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Partner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentTypeID, "DocumentTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DocumentTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DocumentTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartnerHeadOfFamilyID, new { htmlAttributes = new { @class = "hidden" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (Model == null)
{
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
else if (Model.PartnerHeadOfFamilyID == 0)
{
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
else
{
    <div>
        @Html.ActionLink("Back to List Family Group", "IndexFamilyGroup", new { id = Model.PartnerHeadOfFamilyID })
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ACS/Views/Partners/Delete.cshtml
@model ACS.Models.Partner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocumentType.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentType.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ACS/Views/Partners/Details.cshtml
@model ACS.Models.Partner

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Partner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DocumentType.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentType.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DocumentNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMail)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PartnerID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@*<p>
    @Html.ActionLink("Add Family", "CreateFamily", new { id = Model.PartnerID}, new { @class = "btn btn-primary" })
</p>*@

ACS/Views/Partners/Edit.cshtml
@model ACS.Models.Partner

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Partner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PartnerID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DocumentNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DocumentNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentTypeID, "DocumentTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DocumentTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DocumentTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EMail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EMail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EMail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartnerHeadOfFamilyID, new { htmlAttributes = new { @class = "hidden" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@if (Model.PartnerHeadOfFamilyID == 0)
{
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
else
{
    <div>
        @Html.ActionLink("Back to List Family Group", "IndexFamilyGroup", new { id = Model.PartnerHeadOfFamilyID })
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ACS/Views/Partners/Index.cshtml
@model IEnumerable<ACS.Models.Partner>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-primary" })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DocumentType.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DocumentType.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DocumentNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMail)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PartnerID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PartnerID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PartnerID }) |
            @Html.ActionLink("FamilyGroup", "IndexFamilyGroup", new { id = item.PartnerID }) |
            @Html.ActionLink("Cuotas", "Index", "MonthlyFees", new{ id = item.PartnerID}, null)
        </td>
    </tr>
}

</table>

ACS/Views/Partners/IndexFamilyGroup.cshtml
@model IEnumerable<ACS.Models.Partner>

@{
    ViewBag.Title = "Index Family Group";
}

<h2>Family Group</h2>

<p>
    @Html.ActionLink("Add Family", "CreateFamily", new { id = ViewBag.PartnerHeadOfFamilyID }, new { @class = "btn btn-primary" })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DocumentType.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DocumentNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMail)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentType.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DocumentNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EMail)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PartnerID }) |
                @Html.ActionLink("Sports List", "SportList", new { id = item.PartnerID })
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back to List Partners", "Index")
</div>

ACS/Views/Partners/SportList.cshtml
@model ACS.ViewModels.PartnerSportView
@{
    ViewBag.Title = "Sport List";
}
<h3>Sport List of: @Model.Partner.FullName</h3>


<p>
    @Html.ActionLink("Add Sport", "AddSport", new { }, new { @class = "btn btn-primary" })
</p>
<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Sport.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sport.Employee.FullName)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.Sports)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.FullName)
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteSport", new { sportID = item.SportID, partnerID = Model.Partner.PartnerID })
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to List Family Group", "IndexFamilyGroup", new { id = Model.Partner.PartnerHeadOfFamilyID})
</div>

