ACS/ViewModels/RoleView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ACS.ViewModels
{
    public class RoleView
    {
        public string RoleID { get; set; }

        public string Name { get; set; }
    }
}

ACS/ViewModels/UserView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ACS.ViewModels
{
    public class UserView
    {
        public string UserID { get; set; }

        public string Name { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public RoleView Role { get; set; }

        public List<RoleView> Roles { get; set; }
    }
}

ACS/Controllers/UsersController.cs
using ACS.Models;
using ACS.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACS.Controllers
{
    [Authorize(Roles ="Administrator")]
    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        public ActionResult Index()
        {
            var users = GetUsers();
            var usersView = new List<UserView>();

            foreach (var user in users)
            {
                var userView = new UserView
                {
                    UserID = user.Id,
                    Name = user.UserName,
                    Email = user.Email
                };
                usersView.Add(userView);
            }
            return View(usersView);
        }

        // GET: Roles
        public ActionResult Roles(string userID)
        {
            var users = GetUsers();
            var user = users.ToList().Find(u => u.Id == userID);
            if(user == null)
            {
                return HttpNotFound();
            }

            var roles = GetRoles();
            var rolesView = new List<RoleView>();

            foreach (var item in user.Roles)
            {
                var role = roles.ToList().Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    RoleID = role.Id,
                    Name = role.Name
                };
                rolesView.Add(roleView);
            }

            var userView = new UserView
            {
                UserID = user.Id,
                Name = user.UserName,
                Email = user.Email,
                Roles = rolesView
            };

            return View(userView);
        }

        // GET: AddRole
        public ActionResult AddRole(string userID)
        {
            var users = GetUsers();
            var user = users.Find(u => u.Id == userID);
            if(user == null)
            {
                return HttpNotFound();
            }
            var userView = new UserView
            {
                UserID = user.Id,
                Name = user.UserName,
                Email = user.Email
            };

            
            var list = GetRoles();
            list.Add(new IdentityRole { Id = "", Name = "[Select a Role]"});
            list = list.OrderBy(l => l.Name).ToList();
            ViewBag.RoleID = new SelectList(list, "Id", "Name");

            return View(userView);
        }

        // POST: AddRole
        [HttpPost]
        public ActionResult AddRole(string userID, FormCollection form)
        {
            var roleID = Request["RoleID"];

            var users = GetUsers();
            var roles = GetRoles();

            var user = users.Find(u => u.Id == userID);

            var userView = new UserView
            {
                UserID = user.Id,
                Name = user.UserName,
                Email = user.Email
            };

            // Verifico si se selecciono algun rol
            if (string.IsNullOrEmpty(roleID))
            {
                ViewBag.Error = "You must select a role.";

                var list = GetRoles();
                list.Add(new IdentityRole { Id = "", Name = "[Select a Role]" });
                list = list.OrderBy(l => l.Name).ToList();
                ViewBag.RoleID = new SelectList(list, "Id", "Name");
                return View(userView);
            }

            var role = roles.Find(r => r.Id == roleID);
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            if (!userManager.IsInRole(user.Id, role.Name)){
                userManager.AddToRole(user.Id, role.Name);
            }

            var rolesView = new List<RoleView>();
            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);

                var roleView = new RoleView
                {
                    RoleID = role.Id,
                    Name = role.Name
                };
                rolesView.Add(roleView);
            }
            userView.Roles = rolesView;

            return View("Roles", userView);
        }

        public ActionResult Delete(string userID, string roleID)
        {
            if(string.IsNullOrEmpty(userID) || string.IsNullOrEmpty(roleID))
            {
                return HttpNotFound();
            }
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            var user = GetUsers().Find(u => u.Id == userID);
            var role = GetRoles().Find(r => r.Id == roleID);

            if(userManager.IsInRole(user.Id, role.Name))
            {
                userManager.RemoveFromRole(user.Id, role.Name);
            }
            var users = GetUsers();
            var roles = GetRoles();

            var rolesView = new List<RoleView>();
            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    RoleID = role.Id,
                    Name = role.Name
                };
                rolesView.Add(roleView);
            }

            var userView = new UserView
            {
                UserID = user.Id,
                Name = user.UserName,
                Email = user.Email,
                Roles = rolesView
            };

            return View("Roles", userView);
        }

        // Methods

        public List<IdentityRole> GetRoles()
        {
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
            var roles = roleManager.Roles.ToList();
            return roles;
        }

        public List<ApplicationUser> GetUsers()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            return users;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ACS/Views/Users/AddRole.cshtml
@model ACS.ViewModels.UserView

@{
    ViewBag.Title = "AddRole";
}

<h2>Add rol to User: @Model.Name</h2>
<h4 class="text-danger">@ViewBag.Error</h4>

@using (Html.BeginForm("AddRole", "Users", new { userID = Model.UserID}, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <div class="form-group">
            @Html.LabelFor(model => model.Role.RoleID, "RoleID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Role.RoleID, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ActionLink("Return To User", "Roles", new { userID = Model.UserID }, new { @class = "btn btn-info" })
        <input type="submit" value="Add Role" class="btn btn-success" />

    </div>
}

ACS/Views/Users/Index.cshtml
@model IEnumerable<ACS.ViewModels.UserView>

@{
    ViewBag.Title = "Index";
}

<h2>User List</h2>


<table class="table table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Roles", "Roles", new { userID = item.UserID })
            </td>
        </tr>
    }

</table>

ACS/Views/Users/Roles.cshtml
@model ACS.ViewModels.UserView

@{
    ViewBag.Title = "Roles";
}

<h2>Roles to User: @Model.Name</h2>

<p>
    @Html.ActionLink("Add Role", "AddRole", new { userID = Model.UserID }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Back To List", "Index", new { }, new { @class = "btn btn-info" })
</p>


<table class="table table-hover">
    
    @foreach (var item in Model.Roles)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { userID = Model.UserID, roleID = item.RoleID })
            </td>
        </tr>
    }

</table>